### ISSUE TITLE
Rounding mode to nearest 5 or 0

### ISSUE THREAD

**Issue by andyundso** [moneyphp/money#493] opened 2018-08-03 13:56 UTC
Hello everyone

Quick question before I code something: We maintaining an application which is mainly dealing with amounts in Swiss francs. Swiss francs don't know amounts like 1.06 or 5.01, only 1.05 and 5.00.

I found this code sample on [StackOverflow](https://stackoverflow.com/questions/1592352/rounding-mechanism-to-nearest-0-05). Is it possible to do this kind of rounding directly in money?

Thank you very much for your response and best regards

**Comment by frederikbosch** [comment] 2018-08-03 14:40
This is a duplicate of #480

**Closed by frederikbosch** 2018-08-03 14:40 UTC

**Comment by thiagorb** [comment] 2020-06-04 13:25
Hello @frederikbosch. Maybe I am missing something, but I don't think the best solution is to just round the final Money value.

If I try to allocate CHF 1.15 in three equal ratios for example, I would expect to have the money values CHF 0.40, CHF 0.40 and CHF 0.35.

But if I try to allocate it with the current implementation I will get CHF 0.39, CHF 0.38 and CHF 0.38. Rounding these values independently will result in a total of CHF 1.20.

Wouldn't be an option to store the values internally as units of 5 cents? So, CHF 1.15 would be stored as 23. Then, the allocation would result in 8, 8 and 7, and multiplying by the cents units we get the desired end result.
