### ISSUE TITLE
Money\Money is final

### ISSUE THREAD

**Issue by renepenner** [moneyphp/money#322] opened 2016-10-29 17:04 UTC
Why is the Money Class final and not implements a interface?
- I can't Mock the Class in php unit.
- I cant't decouple your lib from my Project via a Proxy Class -> no extend possible.

may i miss understand something

**Comment by sagikazarmark** [comment] 2016-10-29 17:09
Because it's a Value Object and it doesn't make sense to have alternative implementations and as such an abstraction is not necessary.

Mocking value objects is an anti-pattern, since it represents a value. You should instead use dummy values, like `$money = new Money(1234, new Currency('XYZ'));`

For most of the custom behaviour that you might need there is a functional solution too, which is more suitable in this case and does not require inheritance. I am not 100% sure why you would need a Proxy class.

Hope it helps. I definitely have to write a blog post about this.

**Comment by matt-usurp** [comment] 2016-11-01 13:41
I was surprised by this `final` declaration also.

I can agree that mocking a value object is an anti-pattern, however by declaring with `final` we cannot make use of interfaces that the decoupled code base would rely on. For example, we have a `MonetaryValueInterface` that is used and luckily all the methods you supply map with what we require (with some minor parameter name changes). Unfortunately I cannot simply implement your library doing something like `class MonetaryValue extends Money implement MonetaryValueInterface` as I have been able to do with past libraries. Instead I am faced with a pretty massive refactor OR I must create a `MoneyProxy` that constructs an instance of `Money` under the hood and just manipulates it with some rather pointless looking method calls.

For clarification, I used to use `sebastian/money` before it got deprecated, then for some reason moved to `mathiasverraes/money` before realising that this library was its origin and moved to this.

**Comment by sagikazarmark** [comment] 2016-11-01 14:12
@matt-usurp composition is a perfect solution in this case if you need to use your own API and need the behaviour of Money. Although I don't see a reason why you couldn't use Money in your own abstraction. Since it's a final value object you can safely rely on it in your own interfaces.

**Comment by matt-usurp** [comment] 2016-11-01 14:41
I was going to write a massive chunk here about my implementation but really it doesn't matter. 

The crux of the issue is that the library supplies an implementation of `Money` that you consider final but people will want to build upon. Locking it down (c94206304b6dac6ca44c52c99cdd7f806f8e318c) is a very hostile choice in my opinion. The final (in this case) should be made by the developer in the application its used.

**Comment by bmeynell** [comment] 2016-11-01 15:09
> I was going to write a massive chunk here about my implementation but really it doesn't matter.

What's the use case?

**Comment by matt-usurp** [comment] 2016-11-01 15:41
@bmeynell It really doesn't matter as its business logic and I am not going copy the code here. Although as I said above we have an interface that is used all over the code base. In more detail though it requires that an instance of the `AppBundle\Entity\Currency` is passed around with the `Money`. Funnily enough we cannot even extend `Money\Currency` because it is `final` too.

The issue was marked as `question` which implies that there can be input. I am now confused as to why this hasn't been closed yet.

Ultimately, putting the `extend` and `final` fight to a side, why are there no `MoneyInterface` and `CurrencyInterface` for us to provide implementations of?

**Comment by sagikazarmark** [comment] 2016-11-01 15:47
> The crux of the issue is that the library supplies an implementation of Money that you consider final but people will want to build upon.

Which you can do. You can't extend it, because inheritance does not make any sense. There is a functional solution for almost all the issues that you could list.

> It really doesn't matter as its business logic

If it is business logic, then it has nothing to do with the Money VO.

> I am now confused as to why this hasn't been closed yet.

Mostly because we are trying to help people understand that this is not a bad thing and there is a solution for their use case too.

> why are there no MoneyInterface and CurrencyInterface for us to provide implementations of?

Because they are value objects and it doesn't make sense to provide alternative implementations as they would essentially be the same.

Blog post became B+ prio now.

**Comment by matt-usurp** [comment] 2016-11-01 16:43
> There is a functional solution for almost all the issues that you could list.

Sure, and I as you said above "composition is perfect". This is what I had already started writing yesterday, however I decided to check the issues (or even create one) to ask this exact issue. In many ways I regret even writing here.

> Because they are value objects and it doesn't make sense to provide alternative implementations as they would essentially be the same.

This is an excellent way of thinking, "I have done it already so use mine". They _would be essentially the same_ except they are not, I need to convert my currency object to yours then convert it back again once its been passed along the chain of services, in most cases the original currency will be lost and it will probably triggering an additional database query to get it back. All because my currency (although having the same methods exactly) has one additional property in it which is its database primary key (`$id`) but you won't let me use it. This is what I mean by business logic. An interface would also fix this.

Really, I understand why `final` is used. I understand the bonuses of doing this, how it prevents issues being raised for user-land created issues and such. I have read through the google discussions and the various blogs (even the one by the previous owner). Like I get it. I just cannot say that I agree 100% with the design decisions made in this latest release.

**Comment by sagikazarmark** [comment] 2016-11-01 16:55
> In many ways I regret even writing here.

I am sorry for that.

Here is my solution for scenarios like this (although haven't tested yet), we are going to provide that as doctrine embeddable:

``` php
// ..

private $amount;

private $currency;

public function getMoney() : Money
{
    return new Money($this->amount, new Currency($this->currency));
}

public function setMoney(Money $money)
{
    $this->amount = $money->getAmount();
    $this->currency = $money->getCurrency()->getCode();
}
```

Since in case of value objects equality does not depend on the object reference, you are free to create new objects every time you want to get the value. Although it might be a little bit redundant in terms of the currency codes stored multiple times, I see no harm in that as joins might hit the performance more than storing the code instead of a foreign id.

**Comment by matt-usurp** [comment] 2016-11-01 17:10
> I am sorry for that.

Its fine, rather me talk here than everyone just sit on their hands keeping quiet.

Agreed, this is how I have fixed it in most places. As for your embeddable idea I wanted this originally before I even needed to upgrade to `money@3.0` but sadly doctrine embeddable's do not support foreign keys as of yet.

I still have to create a wrapper or composition class to house this though as it needs to go through my existing classes, I don't want to add a hard dependency to your money package in our code base as that goes against our decoupled practices. This was really where I just wanted to extend to implement the interface and move on (this is what I was getting at in my original message).

**Comment by sagikazarmark** [comment] 2016-11-01 17:12
> This was really where I just wanted to extend to implement the interface and move on (this is what I was getting at in my original message)

Well, to be honest I don't see how relying on external interfaces is less coupling than using external implementation.

Anyway, if you really need custom logic, you can always fork this repo and use your custom version (as I needed to in some very specific cases as well)

**Comment by frederikbosch** [comment] 2016-11-04 10:40
@sagikazarmark We should discussing these things. Your time more valuable than to answer this again again and again. Sorry for those who do not understand/agree with our design decisions. We should reference our docs where we explain things, and that's it. Not happy? Start your own library and design things for yourselve.

**Closed by frederikbosch** 2016-11-04 10:40 UTC
Labels: question

**Comment by sagikazarmark** [comment] 2016-11-04 10:54
I've started to write a blog post with examples where I provide solutions for some scenarios, not sure when it will become a thing though.

**Comment by frederikbosch** [comment] 2016-11-04 10:55
And to that guy that is creating a currency in database with an id (instead of the value as the primary key): you do not understand the difference between an entity/model and a value. Once an object is not identified by its value but rather with its id: it becomes an entity/model in your application and you should you start to model things differently. You are probably running a database driven app, versus the domain driven concept of this library.

**Comment by wimby** [comment] 2016-12-27 00:20
@sagikazarmark @frederikbosch 
> You can't extend it, because inheritance does not make any sense.

Sorry, but this argument is invalid. Just because something is a Value Object does not mean it make sense to make it final:
```php
class CzechMoney extends Money {
    function __construct($amount) {
        parent::__construct($amount, new Currency('CZK'));
    }
}
```
Or more obvious should be different example: what if class `Integer` extends from class `Number`, shouldn't `Number` be final just because it is a Value Object?
How about `OddNumber`? `OddNumber` **IS A** `Number` and **IS AN** `Integer`, if some function accepts number, it should accept odd number as well.

You definitely should remove `final` from classes provided to others, because you never know in what environments it will be used. If anyone want to mock it, it's his/her problem, but look at programmers as adults not kids that don't know how to use it.

P.S.: I would need to extend Money for information if the value is with VAT or not, how should I do this instead of creating my own Money class? Where should I put methods to add or remove VAT?

**Comment by sagikazarmark** [comment] 2016-12-27 00:54
@wimby your example does not justify inheritance at all, in fact, it suggests a very bad design. You should think of a Value Object just like as a scalar type: you don't extend string, int and bool types, do you?

Adding custom domain logic (VAT) to a Value Object is a very bad idea exactly because of the above. You should create a Price class instead (which suites your domain better than Money) and add the price there as Money, the VAT as whatever value as you want. The gross value can be returned from the price object as a new Money value (since it's immutable).

Final classes are not meant to keep developers from stupid things, but to enforce good design...on the library as well.

As said above: you don't mock int values, right? Why would you a ValueObject?

**Comment by frederikbosch** [comment] 2016-12-27 13:17
@wimby Learn about composition, and why/when to use it over inheritance (almost always). Solution to your problem.

```php
<?php
namespace X;

final class Price {

   private $amount;
   private $vat;

  public function __construct(Money $amount, VAT $vat) {
     // ...
  }
}


final class VAT {
  private $exempted = false;
  private $percentage = 0;

  public function __construct ($percentage) {
  }

  public function isExempted() {
    return $this->exempted;
  }

  public static function exempted() {
    $vat = new self(0);
    $vat->exempted = true;
  }
}

**Comment by wimby** [comment] 2016-12-27 14:58
Thanks for quick response and good solution for Price! :)

But it just mean I don't understand difference between `Money` and `Price` (I put that in P.S. section). It doesn't prove that `final` is right here and I still think that two paragraphs above P.S. hold.

> you don't extend string, int and bool types, do you?

Oh I think I would: e.g. `AsciiString` and `Utf8String` can be a good examples. They are `String`, but have different sets of alphabet. Or how about extending `int` to [finite field](https://en.wikipedia.org/wiki/Finite_field) `Z5` or smallint? If some object is immutable doesn't necessarily mean that its type or class should be immutable too. The main rule here should be if extending satisfies Liskov substitution principle (which Price and Money does not. How about adding Price class to this package?).

But main reason, why I think you should remove it is because _"to enforce good design"_ is not true either: final is not just recommendation -- it's **restriction**. If I want to change how Money is going to be JSON encoded (e.g. I want to add some `"$type": "Money"`, so that decoding would be easier and based on `$type` value) I have a serious problem. Same with `__toString` or `__debuginfo`. I can't do this with composition.

P.S.: DateTimeImmutable can be extended and it's really helpful to temporary fix bugs.

**Comment by sagikazarmark** [comment] 2016-12-27 23:15
> But it just mean I don't understand difference between Money and Price

Money is a Value Object, Price is a Domain Object. Price contains domain logic, Money contains logic for handling the monetary value. VAT is domain logic.

> If some object is immutable doesn't necessarily mean that its type or class should be immutable too.

I think you are mixing immutability with inheritance here. Immutability means that the internal state cannot be changed. Inheritance means the class can have children.

> The main rule here should be if extending satisfies Liskov substitution principle

Do you apply Liskov to integer and float. Value Object is a type which represents value. EVERY code that adds any logic besides that is simply wrong. Period.

> final is not just recommendation -- it's restriction

Yes, it is. As you cannot create an extended int type or whatever. I understand that you might want to add behaviour or fix something quickly: for that you can fork the project, as it is not something that requires a programatical solution: eventually (if it is a real bug) the lib should have it, in the meantime you can use a forked version.

> If I want to change how Money is going to be JSON encoded

You can: create a wrapper -> domain object

> P.S.: DateTimeImmutable can be extended and it's really helpful to temporary fix bugs.

I am pretty sure you don't want to fork PHP and build a custom version if there is a bug in DateTimeImmutable. Fortunetaly you can fork this library if you want.

I think more than enough said about why closing the API is a good choice (really, I need to write a blog post about it). In almost every case there is a much better solution than inheritance, so all you need to do is find that solution and enjoy the better design.

**Comment by wimby** [comment] 2016-12-28 00:37
I am looking forward to your blog post, really :-)

there are some good articles about `final`, e.g.: http://ocramius.github.io/blog/when-to-declare-classes-final/
when he states:
> ### When to avoid final:
> Final classes only work effectively under following assumptions:
> 
> - There is an abstraction (interface) that the final class implements
> - All of the public API of the final class is part of that interface
> 
> If one of these two pre-conditions is missing, then you will likely reach a point in time when you will make the class extensible, as your code is not truly relying on abstractions.

You don't have interfaces yet you make it final.

Inheritance means the class can be extended.

Maybe we have different terminology for Value Objects. I understand it as an object thats equality is based on its value (iff two objects represent same values they are considered same). Its natural to make them immutable because changing value changes equality (which can be bad if it is in some hash based collection).

There is nothing about other logic.

Lets take `array` -- its equality with other arrays is based on equality of items and order of the items it contains, so it is a _Value Object_. Arrays are usually mutable, because when it contains lots of items its more efficient. Arrays provide methods for adding, removing and iterating, some serialization methods, some printing or debugging methods, it can have methods for sorting and searching, it can have methods for intersecting and unioning with other arrays and so on. It still make perfect sense to extend `array` for lets say a `Vector` that allows only numbers as its items. I still can add new methods e.g. method for sum or product or multiply with a number...

@sagikazarmark It would help me, if you can show a (good design of course ;-)) solution for (at least) last "question" from my last comment: I need every JSON value that is not string, number, bool or null (JSON primitives) to be a (JSON) object with `"$type"` property equal to class name of the (PHP) object.
```php
class Money implements JsonSerializable
{
    function jsonSerialize() {
        return [
            '$type' => 'Money',
            'amount' => $this->amount,
            'currency' => $this->currency,
        ];
    }
}
```
How can I do it?

**Comment by sagikazarmark** [comment] 2016-12-28 01:52
I don't think it's the terminology we think about differently, rather the practical usage. In almost all the cases above (and in other issues) people wanted to add their domain logic to a Value Object. I think we can agree that this is just wrong, don't do it. This is what the final keyword enforces: no domain logic.

Looking at the current implementation, I think Money provides everything I can think of which can be useful for handling a monetary value...without any kind of domain logic. This might not be true, but let's assume for a moment that it is. This means that any behaviour that you might want to add is something that is only necessary for your domain. According to the above (from a design perspective, not from the pure definition of Value Objects) this is wrong, so adding it to the Money value is a bad idea (no matter if the code is in this library or not). Since inheritance is not allowed (which would let us do tha above), the final keyword is justified, which does not only mean you cannot extend it, but also enforces you a kind of design which should be followed by consuming code. While this might sound crazy, I don't think following the mentality of a library is wrong.

Since there is no perfect implementation, this is probably isn't one either, but I still haven't heard a use case where inheritance would be justified. It's misused in most of the cases and there is usually another solution, which might not be simpler, but better designed.


All in all: Money is not final, because it is a Value Object. It is final, because we see no reason NOT to be final. As soon as you bring me 3 valid reasons where inheritance is your only/best option we might think about opening the API. I haven't heard any so far.

The proper solution (IMO) for your problem is having a separate serialization layer which normalizes your money object as you wish. For example you can do it with Symfony Serializer component or with your custom serialization layer. I admit that this serialization feature is quite opinionated, but to be honest: I wouldn't use it at all.

**Comment by wimby** [comment] 2016-12-28 03:00
Why you need three reasons? One valid reason should be enough :D

More interesting is what you consider _valid_. Final keyword doesn't enforce _no domain logic_, it enforces _no any logic, no extending at all_.

Maybe we should define **domain logic**.
For me Domain is set of objects from real world with its interactions. Money is definitely object from real world, it is basic building block for ecommerce or banking software. I can have in my domain some Money that is considered safe, lets say 100 dollars. If something is over this value, lets say a signature is required.

Having class `SafeMoney` in my Domain is perfectly _valid_. `SafeMoney` [**is_a**](https://en.wikipedia.org/wiki/Is-a) `Money`. It can extend Money for some safety threshold value. Why you consider this bad design? For me this is THE (only) solution.

Just because something is in package (or library) does not mean it can't be part of Domain.

I would like to hear your definition of domain logic :-)

**Comment by sagikazarmark** [comment] 2016-12-28 09:02
> Why you need three reasons? One valid reason should be enough :D

Well, I am not fair: I don't think there are valid reasons, only validish ones and from those one is not enough.

Let me turn the question: why do you think inheritance is the only/better solution?

What you are trying to add here is a behaviour to a Value Object. I have several problems with that:

- There is no real multiple inheritance, so if you need multiple behaviours what do you do? (Composition solves this problem)
- Although VO definition does not say anything about custom behaviour, I still think that fundamentally VOs are only meant to represent a value and expose the minimum set of features which is necessary to interact with that value. Not technically correct, but this is why I compare them to scalar types.
- Value representation usually involves some kind of serialization. Inheritance makes this harder as you have to manage multiple options (types of the same VO, even this sounds like an abomination)

I am a little bit tired of proving the same point over and over again (not to mention that others already did quite a few times, read the linked posts in Ocramius's post). If you go through the issues (there were more than this one) you will find that in almost all cases @frederikbosch or I provided a solution with composition which in the end turned out to be a better and accepted solution.

If you REALLY need inheritance, there is no way that you find another solution (which is guaranteed to be better as per the above IMO) then you are free to fork this library and maintain a custom one with removed final keyword. You can always update that fork based on MoneyPHP without any problems.

**Comment by wimby** [comment] 2016-12-29 00:18
Hello again... 
> why do you think inheritance is the only/better solution?

Because (a) there is no interface for Money, if some function, lets say `function pay(Money $m)` accepts Money in typehint, there is no other way. And (b) its not about inheritance or polymorphism, is about extension. The keyword is `extends` no _inherits_. You [**closed**](https://en.wikipedia.org/wiki/Open/closed_principle) Money (and Number) for **extension**.

> What you are trying to add here is a behaviour to a Value Object.

No. I have _extended_ Money for safety threshold property which is a value. And -- this is harder to spot -- I have added _some semantics_ with SafeMoney class. Its still a Value Object, it makes no decisions, no added logic.

If you think that `final` makes class better, then its only a religion. If you leave class without final, it can be used in same ways as _with_ final. If you add final, you make it [weaker](http://math.stackexchange.com/questions/53708/precise-definition-of-weaker-and-stronger).

**Comment by sagikazarmark** [comment] 2016-12-29 05:43
> Because (a) there is no interface for Money, if some function, lets say function pay(Money $m) accepts Money in typehint, there is no other way.

No other way...for what? I don't see an argument here.

The more I think about this SafeMoney example the more I think that it's actually a business logic rule forced into a Value Object.

> The keyword is extends no inherits.

Sorry, what? Extension and the extends keyword are not the same. Extension means that we have some kind of extension points (plugins, events, etc), composition strategies, etc. The extends keyword is used for inheritance in PHP (and many other) language.

> You closed Money (and Number) for extension.

We closed it for inheritance and haven't described any extension points, so basically composition is all you have. You could say that this is closed for extension, but it's not really correct.

> No. I have extended Money for safety threshold property which is a value. And -- this is harder to spot -- I have added some semantics with SafeMoney class.

As I mentioned above I believe that you are trying to put your business logic into a value object. Business rules change, Value Objects don't: Tomorrow you might require every user called Bob to give DNA before paying in USD between $4.99 and $5.50. Would you put that into the Money object as well?

> it makes no decisions, no added logic.
That's the whole point of the feature you added: to make a decision about the value...based on a property. Or did I miss something?

**Comment by wimby** [comment] 2016-12-29 18:11
Inheritance and interfaces are used to model _IS-A_ relationship, compositions and aggregations are used to model _HAS-A_ relationship. PHP's type system is based on IS-A relationship only. No objections here I guess.

> No other way...for what?

If some function requires Money, there is no way to use composition, because type system won't accept objects that are-not-a Money.

> ... it's actually a business logic rule forced into a Value Object.

You _should_ really define domain or business logic, otherwise it loses any point here.
The business logic is _outside_ SafeMoney -- SafeMoney is object that says: I'am Money (IS-A) and I have some adjective Safe which is a parameter. If you don't care about Safeness use me the same way as you use Money.

> Extension means that we have some kind of extension points (plugins, events, etc), composition strategies, etc.

Let me read the article for you:
> A module will be said to be open if it is still available for extension. For example, it should be possible to add fields to the data structures it contains, or new elements to the set of functions it performs.

Adding a field or new set of functions is usually done with inheritance. Of course you can create your custom way of extending classes, but unless PHP let you change IS-A behaviour, it won't work with current type system and you actually won't be extending (adding an item to an array won't extend the type of an array).

> You could say that this is closed for extension, but it's not really correct.

Any arguments here?

> Would you put that into the Money object as well?

No, because _pay_ it is not Money's method. But I _can_ extend Money for `MoneyWithDNA` that will carry Bob's DNA.

If everything you want (with final) is better design for everyone, then just remove final and let users themselves decide if they _need_ inheritance or if composition is better for them. Money will be [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and pragmatic. It's _that_ easy.
If you are tired of explaining why composition is almost always better again and again, you can write an article and just link it (or find an article there are lots of them), but don't deny inheritance. It has its well established and unreplaceable (if there is no interface) place.

**Comment by sagikazarmark** [comment] 2016-12-30 04:48
> If some function requires Money, there is no way to use composition, because type system won't accept objects that are-not-a Money.

This only matters if you actually want to use Money as a type in your functions/methods. If you use composition (like a Price object) you can put whatever there which suits your needs.

> You should really define domain or business logic, otherwise it loses any point here.

Based on how do you decide if a money is safe or not? How is this condition originated from the Money value? IMO this is something that YOU define and use in your code  to decide how it should behave. This rule is probably subject of change, might be combined with others, etc. So I would put this kind of validation in a different layer which collects your rules and tells you if your money and/or other data passes these rules. Not sure if I understood your use case well, but I am not convinced that this requires inheritance.

> Let me read the article for you

I know the "classical" (original) approach for OCP, but I simply can't accept to narrow down the term "extension" to inheritance. Neither [John Skeet](https://codeblog.jonskeet.uk/2013/03/15/the-open-closed-principle-in-review/) nor [Mathias Verraes](http://verraes.net/2014/05/final-classes-in-php/) and I am pretty sure there are other people.

As such, I don't think Money is closed for extension.

I don't deny that inheritance is the easier way. I know that the lack of an interface makes extension even harder, but is there an alternative implementation that makes sense and is different from the current one?

> No, because pay it is not Money's method. But I can extend Money for MoneyWithDNA that will carry Bob's DNA.

But you want it to be safe as well! `SafeMoneyWithDna`? What about single responsibility?

**Comment by wimby** [comment] 2016-12-30 14:53
> Based on how do you decide if a money is safe or not? How is this condition originated from the Money value? IMO this is something that YOU define and use in your code to decide how it should behave. This rule is probably subject of change, might be combined with others, etc. So I would put this kind of validation in a different layer which collects your rules and tells you if your money and/or other data passes these rules.

Exactly. My rules could be like this: "Money is told to be Safe if it is under some arbitrary value. With Safe Money user is not required to sign transaction."
So how can you tell if Money is Safe? I can put this validation to a different layer (everywhere where its necessary and if something changes I need to find these places... there must be a better way). Or realize that Safe is a property of Money and can be lost with addition and multiplication and gained with subtraction and division. So I can create class SafeMoney with method isSafe() which covers this validations. Do we agree here? Now SafeMoney IS Money... damn I need to use SafeMoney everywhere even where I am fine with just Money.

> As such, I don't think Money is closed for extension.

Thanks for articles. Can you show me how you extend Money please?

> but is there an alternative implementation that makes sense and is different from the current one?

There is ALWAYS an alternative implementation. If you don't like `SafeMoney`, there are many more others: with double (or defined) subunit precision, with different rounding rules, without rounding at all, using just integers (more efficient but with limited amount)... usually if I have business rules for USD only it makes sense to have `UsdMoney`.

> What about single responsibility?

Its still _something_ to pay with.

If you don't want to remove final from Money, you can create an interface `MoneyInterface` and IS-A relationship would be achievable with that too.

**Comment by TrogWarZ** [comment] 2017-02-09 09:00
I agreed with that Money must be just immutable value object, but there always can be alternatives that will leave it as VO but add some semantics, decorate, typehinting, make more dry and so on.

Even if i want to do something "bad" like add some method called "payThisToJohnOrNancy" – that will add decision and behaviour, yes.. but why do you deny me to do that? Talks about "bad" or "good" practices are holywars IMO but let me (as a developer of my software) decide that.

I personally like the way of libraries to stay minimalistic and don't add features that don't need majority of devs – other examples are already provided by other commentators like "UsdMoney", "PaypalMoney", "getPercentageOf", etc (that will stay only VO and possibly will have "final"-keyword in my project after extension). But there is need adequate way to add them if i need and this library doesn't have them.

> you can always fork this repo and use your custom version

Yes, i can fork library but i don't like to reinvent the wheel because it will be another project – to add force to this "money abstraction" i need to remove final, change `new self` to `new static`, add interfaces... and, hardest thing, community – this library, for example, used in `tbbc/money-bundle` (and many others). So, if i fork money, i need to fork another libraries (maybe, not just one) too. Big changes and headaches due to lack of force.

**Comment by frederikbosch** [comment] 2017-02-09 09:01
Let's keeping discussing a topic that has been closed for months. `Money` is final, period.
