### ISSUE TITLE
Problems with string casting and locales that use comma as separator

### ISSUE THREAD

**Issue by Surt** [moneyphp/money#358] opened 2017-03-10 11:00 UTC
Triying to do something similar to this: 

```
$money = Money::EUR(100); 
$percentage = $money->multiply(10 / 100);
$result = $money->subtract($percentage);
```

but it returns 0€ for $percentage. Any clue? The system does have the bcmath extension loaded.

**Comment by Surt** [comment] 2017-03-10 11:11
By the way, triying to do this:

```
/** @var \Money\Money $start */
$start = Money::EUR(399);
$ht = $start->divide(1.2);
echo $ht->getAmount()."\n";
```

gives me a `InvalidArgumentException: Division by zero` maybe it's something related to the php configuration?

**Comment by sagikazarmark** [comment] 2017-03-11 08:07
I think this is related to #352

**Comment by frederikbosch** [comment] 2017-03-11 10:45
Think so too.

**Comment by frederikbosch** [comment] 2017-03-11 10:46
Will close it after that one is merged in. If the problem is not solved, we can reopen it.

**Comment by Surt** [comment] 2017-03-13 08:13
still `InvalidArgumentException: Division by zero`  on master

**Comment by Surt** [comment] 2017-03-13 08:23
It doesn't  happend when using strings for values in operations, instead of numbers....

**Comment by frederikbosch** [comment] 2017-03-13 13:10
@Surt I will take care of this. You can expect fixes tomorrow.

**Comment by frederikbosch** [comment] 2017-03-14 10:25
@Surt I cannot replicate this. I tried the following.

```php
Money::registerCalculator(new BcMathCalculator(0));
$money = new Money(399, new Currency(self::CURRENCY));
$this->assertSame('333', $money->divide(1.2)->getAmount());

Money::registerCalculator(new GmpCalculator());
$money = new Money(399, new Currency(self::CURRENCY));
$this->assertSame('333', $money->divide(1.2)->getAmount());

Money::registerCalculator(new PhpCalculator());
$money = new Money(399, new Currency(self::CURRENCY));
$this->assertSame('333', $money->divide(1.2)->getAmount());
```

I tried PHP 5.6 and PHP 7.0. Could you share your system settings: what php version are you using? Do you have BCMath or GMP enabled? That is not required btw, but it tells me which calculator your setup is using.

**Comment by Surt** [comment] 2017-03-14 12:07
Hi,

```
PHP 5.6.30 with 
BCMath support => enabled
Directive => Local Value => Master Value
bcmath.scale => 0 => 0
```

I'm using php-fpm through nginx

**Comment by Surt** [comment] 2017-03-14 12:26
When debuggin I saw

`$this->getCalculator()->compare((string) $divisor, '0') === 0` // /vendor/moneyphp/money/src/Money.php (line 329)

Maybe it's due to the Locale settings?

**Comment by frederikbosch** [comment] 2017-03-14 15:01
@Surt But that is not a problem that this library is causing. We expect actual numbers, not localized numbers. So I guess there is no bug left in our repo that is causing your problems, right?

**Comment by Surt** [comment] 2017-03-14 15:13
@frederikbosch I'm sending a number, but the library cast it to string, wich causes the problem. To be aware of scalar types must be a must-do. I've solved it, but using an ugly patch. 
Whoever is using the library as me will found a problem wich is related to that casting, except for some lucky ppl with default configuration been the one under the library was programed. 

As I said, I solved it sending the number already casted and using str_replace but... as I see it if I'm sending a float I expect the system to take that float, not a particular cast of it.

**Comment by frederikbosch** [comment] 2017-03-14 15:17
@sagikazarmark WDYT about this? Should we change our code because of it?

@Surt A better solution (instead of `str_replace`) is `sprintf('%.8g', $value)`

**Comment by frederikbosch** [comment] 2017-03-14 15:18
@sagikazarmark We could replace `(string)` with `(string) Number::fromString()`. The question, do we want that?

**Comment by Surt** [comment] 2017-03-14 15:23
`echo sprintf('%.8g', 1.3);`
gives me `'1,3'` with comma instead of dot.

I know it is a weird php behaviour, but also, if you decide not to take this in consideration it must warn the users about this particularity.

**Comment by frederikbosch** [comment] 2017-03-14 15:27
@Surt That is for sure.

@Surt How about `echo sprintf('%.8G', 1.3);`

**Comment by Surt** [comment] 2017-03-14 15:33
```
        printf('%.8g', 1.3);  // "1,3"
        printf('%.8G', 1.3); // "1,3"
        printf('%.8F', 1.3); // "1.3"
```
http://php.net/manual/en/function.sprintf.php
F - the argument is treated as a float, and presented as a floating-point number (non-locale aware). Available since PHP 5.0.3.

so, "%.8F" seems to be the way to go.

**Comment by frederikbosch** [comment] 2017-03-14 15:34
Cool. Thanks.

**Comment by frederikbosch** [comment] 2017-03-19 14:57
@Surt PR #361 will solve the issue.

**Closed** 2017-03-20 12:21 UTC
