### ISSUE TITLE
Integer validation allows empty string as value

### ISSUE THREAD

**Issue by sagikazarmark** [moneyphp/money#340] opened 2016-12-27 00:29 UTC
@frederikbosch it seems to be possible and it seems to be a bug to me. Question is: is this a bug that we should/can fix in a BC manner? As far as I can see right now `Number::fromString('.123')` is possible which is not obviously wrong IMO, question is if we should think about it as a side effect and fix it or not.

**Comment by frederikbosch** [comment] 2016-12-27 11:39
I think this is as correct as 3.0000, which is also allowed. So not a bug to me. But I think it is wise to add a test for it and as such make it a tested feature.

**Comment by frederikbosch** [comment] 2016-12-27 16:40
This is tested now in my alternative solution for #338.

**Comment by frederikbosch** [comment] 2017-02-14 20:52
Will be merged by #341.

**Closed by frederikbosch** 2017-02-14 20:52 UTC
