### ISSUE TITLE
min & max methods

### ISSUE THREAD

**Issue by zlanich** [moneyphp/money#497] opened 2018-09-03 20:14 UTC
It would be nice (and simple) to add a min() & max() methods to the Money class. I made my own that I use all the time for things like values that can't be less than 0 - ie. `return $amount->max(Money::USD(0));`

**Comment by sagikazarmark** [comment] 2018-09-08 04:53
This feature was implemented in #478, waiting for release.

**Comment by zlanich** [comment] 2018-09-08 06:32
Awesome! Thank you.


Best Regards,

Zach Lanich
*Business Owner, Entrepreneur, Creative*
*Owner/CTO*
weCreate LLC
*www.WeCreate.com <http://www.WeCreate.com>*

From: Márk Sági-Kazár <notifications@github.com> <notifications@github.com>
Reply: moneyphp/money
<reply@reply.github.com>
<reply@reply.github.com>
Date: September 8, 2018 at 12:53:16 AM
To: moneyphp/money <money@noreply.github.com> <money@noreply.github.com>
CC: zlanich <zach@zachlanich.com> <zach@zachlanich.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [moneyphp/money] min & max methods (#497)

This feature was implemented in #478

**Comment by frederikbosch** [comment] 2018-09-12 14:46
Duplicate of #499

**Closed by frederikbosch** 2018-09-12 14:46 UTC
