### ISSUE TITLE
Fractions of a cent

### ISSUE THREAD

**Issue by CMCDragonkai** [moneyphp/money#40] opened 2014-01-09 15:48 UTC
Does this work for fractions of a cent? How accurate is it if I use the multiply and pass in something like 0.1234?

**Comment by keiosweb** [comment] 2015-02-08 18:13
announcing [Keios/MoneyRight](https://github.com/keiosweb/moneyright) - bcmath based money object heavily based on your work @mathiasverraes, we were using your library, so MoneyRight has API matching 1.2.1 release and can work as drop-in replacement for projects depending on GAAP 4 decimal points precision.

**Comment by niepi** [comment] 2015-06-25 16:50
This is also a problem when you use allocate with floats and you have results that have fractions of cents. Those then are cut off and will lead to errors. I don't think this is technically a bug, but I was not aware of this.

```
        if ($discountValue > 1) {
            $discountValue = $discountValue / 100;
            $remainingValue = 100 - $discountValue;
            list($discount, $remaining) = $money->allocate([$discountValue, $remainingValue]);
            $money = $money->subtract($discount);
        }
````
````$69```` will be ````$63,82```` instead of ````$63,825````

**Comment by frederikbosch** [comment] 2016-01-06 12:29
Let's make this happen too. Why not create a new class `PreciseMoney` as indicated in #111 by @mathiasverraes?

I think we can reuse the calculators are created in PR #115, but rounding should be extended with precision. Only `bcmath` can help us out in this case, because GMP is still waiting for [RFC GMP Floating Point Numbers](https://wiki.php.net/rfc/gmp-floating-point) to be accepted yet.

@sagikazarmark Do you have any specific ideas on this topic?

**Comment by fedeisas** [comment] 2016-03-21 17:59
The rounding should be performed upon instantiation or formatting of the `Money` instances?

**Comment by frederikbosch** [comment] 2016-08-03 12:42
This is a duplicate of #7.

**Closed by frederikbosch** 2016-08-03 12:42 UTC
Labels: pending
